# Generated by Django 4.2.1 on 2023-05-30 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100, verbose_name='title')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=18, null=True, verbose_name='price')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='carmodel',
            name='engine',
            field=models.CharField(blank=True, max_length=100, null=100, verbose_name='engine'),
            preserve_default=100,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(null=True, verbose_name='year'),
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(db_index=True, null=True, verbose_name='quantity')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, max_digits=18, null=True, verbose_name='price')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='garage.order', verbose_name='order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='garage.service', verbose_name='service')),
            ],
            options={
                'verbose_name': 'order entry',
                'verbose_name_plural': 'order entries',
            },
        ),
    ]
