# Generated by Django 4.2.1 on 2023-06-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0002_service_carmodel_engine_carmodel_year_orderentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Not started'), (1, 'In progress'), (2, 'Delivered'), (3, 'Canceled')], default=0, help_text='Status', max_length=2, verbose_name='status'),
        ),
    ]
