# Generated by Django 4.2.1 on 2023-06-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(db_index=True, max_length=20, verbose_name='license_plate'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(db_index=True, max_length=17, verbose_name='VIN'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.CharField(db_index=True, max_length=100, verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='engine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='engine'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(db_index=True, max_length=100, verbose_name='model'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='year'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Nepradėta'), (1, 'Vykdoma'), (2, 'Atlikta'), (3, 'Atšaukta')], default=0, help_text='Statusas', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderentry',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
    ]
