# Generated by Django 4.2.1 on 2023-06-02 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='garage/car_images', verbose_name='image'),
        ),
    ]
