# Generated by Django 4.2.1 on 2023-06-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garage', '0007_car_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='customer',
        ),
        migrations.AddField(
            model_name='car',
            name='note',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='order',
            name='due_back',
            field=models.DateField(blank=True, null=True, verbose_name='due back'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('processing', 'Processing'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='new', help_text='Status', max_length=20, verbose_name='status'),
        ),
    ]
